### ISSUE TITLE
NeoDesk4 installation and usage via GEMdrive fails

### ISSUE THREAD

**Issue by RetroTechN00b** [sidecartridge/atarist-sidecart-raspberry-pico#104]
Firmware 0.16 beta

I tried to install NeoDesk 4 from (physical) floppy  on the GEMdrive. It failed when reordering files in the AUTO folder.

As a workaround I copied a fresh and working NeoDesk 4 installation into the GEMdrive /hd folder. When booting from the GEMdrive I get 4 bombs during the execution of the AUTO folder (I guess). Afterwards the GEMdrive is not accessible.

Tested with identical results:
- 520ST 4MB TOS 1.00
- 1040STF 4MB TOS 1.02
- 1040STE 4MB TOS 1.62

**Comment by diegoparrilla** [comment]
This problem has to do with a bug in the filtering of the FsFirst and FsNext functions. It has been also detected with other software tools.
