### ISSUE TITLE
Boot drive select enhancement?

### ISSUE THREAD

**Issue by Pny** [sidecartridge/atarist-sidecart-raspberry-pico#105]
Since the cartridge is the first thing to be accessed at power on/reset it might (or not?) be possible to implement a true boot selector function in the SidecarT boot firmware? ...making an unmodified Atari, without any hardware soldered boot select switches, boot from external floppy disk drive or other third party floppy emulator such as the Gotek or similar. 

With "true boot select" I mean true bootsector loading from floppy drive B on an Atari STE, not only autofolder booting by changing the register at $446 _bootdev System boot device number.

**Comment by diegoparrilla** [comment]
Version 0.0.18 will allow custom selection of the virtual drives A: or B:

Ex: Drive A as a physical drive/Gotek, Drive B an emulated drive by the device
