### ISSUE TITLE
Mass Storage Device in Configurator Mode

### ISSUE THREAD

**Issue by diegoparrilla** [sidecartridge/atarist-sidecart-raspberry-pico#111]
### Problem
One of the most annoying aspects of starting with the device is populating or creating the microSD card. Currently, users need to remove the card and insert it into a PC/Mac/Linux computer to update its content.

### Proposed Solution
To address this issue, we propose converting the SidecarTridge multi-device into an external USB disk drive when in Configurator mode. In this "Mass Storage Mode," when the device is in Configurator mode and connected to a PC/Mac/Linux via USB, it will appear as an external read-writable drive. This will allow users to easily transfer content back and forth without needing to remove the microSD card.

**Comment by Pny** [comment]
This is a great idea!
