### ISSUE TITLE
enhancement: Show RTC time

### ISSUE THREAD

**Issue by danboid** [sidecartridge/atarist-sidecart-raspberry-pico#131]
When the RTC has been configured, sidecart should print the current time (and date?) in the RTC menu but I'd like to see the time on the main configurator screen too.

Showing the time and/or date on the main screen should both be optional but I'd have it enabled by default, why not?

**Comment by diegoparrilla** [comment]
The date and time are displayed at boot time in the RTC and GEMDRIVE features
