### ISSUE TITLE
RTC fault

### ISSUE THREAD

**Issue by MrYoIt** [sidecartridge/atarist-sidecart-raspberry-pico#144]
Atari STE 4mb ram Tos 2.06

Booting with rtc or gem drive and after booting an ahdi drive, FOLDRXX.PRG changes the year. Hour, day and month are correct but the year returns to 1994.

**Comment by diegoparrilla** [comment]
The issue appears to be specific to how version 2.06 sets the date, conflicting with the code designed to address the Y2K problem. I will work on finding a workaround to properly handle the Y2K issue in version 2.06.

**Comment by diegoparrilla** [comment]
I have committed code for the RTC only that works for all TOS versions with and without the Y2K fix. The code should build in the nightly release tonight.

Hopefully I will also port the code to the GEMDRIVE RTC tomorrow or day after tomorrow to release a maintenance release this weekend.

**Comment by MrYoIt** [comment]
![IMG-20241214-WA0005.jpeg](https://github.com/user-attachments/assets/3b31ae59-6598-4aef-b82a-884d47103f0b)

**Comment by diegoparrilla** [comment]
It sounds like the path is working in the nightly release. I'm testing it and will be released next week as a maintenance release.

**Comment by MrYoIt** [comment]
Yes, in nightly works, with gemdrive too. Playing with Rogue the saves have the right date/hour.
