### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by RetroTechN00b** [sidecartridge/atarist-sidecart-raspberry-pico#94]
On the [getting started page](https://docs.sidecartridge.com/getting_started/#initial-setup-and-configuration) of the documentation the link to the How To page for the SD card formatting is broken.

instead of
`(Optional) A microSD card [formatted as FAT16 or exFAT](https://docs./how_to/#format-the-microsd-card).`

it should be
`(Optional) A microSD card [formatted as FAT16 or exFAT](https://docs.sidecartridge.com/how_to/#format-the-microsd-card).`

**Comment by diegoparrilla** [comment]
Fixed in the new docs path for multi-device

https://docs.sidecartridge.com/sidecartridge-multidevice
